Updating ws package
taskcluster/docker-exec-websocket-server pull request #8
Opened 2016-09-14 15:12 UTC by eliperelman

2016-09-14 15:14 UTC, eliperelman commented
@jonasfj would you mind testing this out, I don't have a docker installation, and I'd like to make sure the tests pass.

2016-09-15 21:27 UTC, jonasfj commented on package.json
> +    "ws": 			"1.1.1",
Any reason not to use `^1.1.0` down streamers should use npm-shrinkwrap.

2016-09-15 21:28 UTC, jonasfj requested changes

2016-09-15 21:29 UTC, eliperelman commented on package.json
> +    "ws": 			"1.1.1",
Fine with me.

2016-09-15 21:29 UTC, jonasfj approved these changes

2016-09-15 21:29 UTC, merged

2016-09-15 21:29 UTC, jonasfj commented
This works...

2016-09-15 21:30 UTC, jonasfj commented
I'll do that change and publish, now that my editor is open :)